/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.TransaccionController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.Validations;

/**
 *
 * @author thatsgonzalez
 */
public class RetirarEfectivo extends javax.swing.JPanel {
    int idCuenta;
    double saldo;
    /**
     * Creates new form RetirarEfectivo
     */
    
    JFrame myFrame;
    Validations validacion = new Validations();
    
    public RetirarEfectivo(JFrame frm, Object[] data) {
        initComponents();
        
        this.myFrame = frm;
        this.idCuenta = Integer.parseInt(data[0].toString());
        this.saldo = Double.parseDouble(data[1].toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setText("Cantidad a retirar:");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void salir(){
        this.setVisible(false);
        myFrame.dispose();
    }
    
    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        if(validacion.isStringEmpty(this.txtDinero.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese el monto a retirar");
            return;
        }
        
        TransaccionController transaccionC = new TransaccionController();
        
        double monto = Double.parseDouble(this.txtDinero.getText());
        
        if(monto < 1){
            JOptionPane.showMessageDialog(this, "El valor a retirar no puede ser negativo y menor a 1");
            return;
        }
        
        int insert = transaccionC.insertTransaccion(-monto, idCuenta, saldo, "Retiro");
        
        if(insert == 1){
            JOptionPane.showMessageDialog(this, "No se puede retirar mas del saldo disponible");
            return;
        }
        if(insert == 2){
            JOptionPane.showMessageDialog(this, "No se puede crear la transaccion");
            return;
        }
        
        JOptionPane.showMessageDialog(this, "La transaccion fue creada con exito");
        salir();
        
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDinero;
    // End of variables declaration//GEN-END:variables
}
