/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.CuentaController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.Validations;

/**
 *
 * @author thatsgonzalez
 */
public class SeleccionCuenta extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionCuenta
     */
    
    private int opcion;
    private JFrame myFrame;
    private int id_cliente;
    Validations validacion = new Validations();
    
    public SeleccionCuenta(int opcion, JFrame frm, int id_cliente) {
        initComponents();
        this.opcion = opcion;
        this.myFrame = frm;
        this.id_cliente = id_cliente;
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCorrelativo = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese el correlativo de la cuenta a utilizar:");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        if(validacion.isStringEmpty(this.txtCorrelativo.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese el numero de cuenta");
            return;
        }       
        
        CuentaController cuentaC = new CuentaController();
        int correlativo = Integer.parseInt(this.txtCorrelativo.getText());
        
        Object[] data = cuentaC.getCuentaById(this.id_cliente, correlativo);
        if(data == null){
            JOptionPane.showMessageDialog(this, "No tienes una cuenta con el correlativo ingresado");
            return;
        }
        switch(opcion){
            case 1:
                
                JFrame f = new JFrame();
        
                RetirarEfectivo panel = new RetirarEfectivo(f, data);
                f.setSize(520,229);
                f.getContentPane().add(panel);
                f.setVisible(true);
                salir();
                break;
            case 2:
                f = new JFrame();
        
                AbonarCuenta panel2 = new AbonarCuenta(f, data);
                f.setSize(714,362);
                f.getContentPane().add(panel2);
                f.setVisible(true);
                salir();
                break;
            case 3:
                f = new JFrame();
        
                VerCuenta panel3 = new VerCuenta(f, data);
                f.setSize(708,271);
                f.getContentPane().add(panel3);
                f.setVisible(true);
                salir();
                break;
            case 4:
                f = new JFrame();
        
                VerTransacciones panel4 = new VerTransacciones(f, data);
                f.setSize(627, 458);
                f.getContentPane().add(panel4);
                f.setVisible(true);
                salir();
                
                break;
            default:
                
                break;
        }
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void salir(){
        this.setVisible(false);
        myFrame.dispose();
    }
    
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCorrelativo;
    // End of variables declaration//GEN-END:variables
}
